src/GUI/LiveView.cpp
Made it more clear that there's a right-click menu for the 'auto-create on startup' opton for watches in LiveView.
This was impossible to know if the user didn't randomly right-click the checkbox.
=> Improved the on-hover notification for the 'Auto-create on startup' checkbox.

src/GUI/Dumpers.cpp
Split 'FStaticMaterial' into two structs, one for <=4.19 and one for >=4.20.
This hopefully means that it's no longer necessary to have separate versions of UE4SS for <=4.19 and >=4.20.
=> Hopefully removed the need for two UE4SS dlls.

Readme.md, Staging/Readme.md, Staging/UE4SS-settings.ini
There is no real reason to not have these 1 by default and by having them 0 by default, people not accustomed with the tool are creating crappy templates.  
Also added my name to readme credits, because I helped Muppet with testing a lot during the early days of UE4SS, but never asked for credit.
=> Changed default UHT dumper settings for forcing flags

src/USMapGenerator/Generator.cpp
This should probably be back-ported to https://github.com/OutTheShade/UnrealMappingsDumper.
=> USMapGenerator: Dumping the entire FName for enum elements.

Staging/Mods/CXXHeaderGeneratorMod/Scripts/main.lua, Staging/Mods/Keybinds/Scripts/main.lua, Staging/Mods/ObjectDumperMod/Scripts/main.lua, Staging/Mods/UHTCompatibleHeaderGeneratorMod/Scripts/main.lua, Staging/Mods/mods.txt, include/UE4SSProgram.hpp, src/Mod.cpp, src/UE4SSProgram.cpp
See the commit for more information about the keybinds mod.
In addition to the keybinds mod:
Added a new global Lua function called "IsKeyBindRegistered". The result is dependent on the mod load order.
Fixed key bindings not getting unbound when hot-reloading mods.
Fixed bug where if you called 'RegisterKeyBind' and passed an empty table for the second parameter, the function passed for the third parameter would get executed regardless if the user is holding any modifier keys.
=> Added 'Keybinds' mod, fixed a couple of bugs, added 'IsKeyBindRegistered'.

include/SDKGenerator/UEHeaderGenerator.hpp, src/SDKGenerator/UEHeaderGenerator.cpp
This bug originated from 5ba7758542dc592b57c98064c4729003908164d0 at line 3120
My commits had their own issues but after they were fixed, they revealed this one. I did not see this bug as I was developing on a commit before 5ba7758542dc592b57c98064c4729003908164d0.
Fixes #36
=> (#36) UHT: Fix module dependencies not getting generated

Staging/API.txt, Staging/Mods/SplitScreenMod/Scripts/main.lua, Staging/Mods/shared/UEHelpers/UEHelpers.lua, include/LuaType/LuaUObject.hpp, include/Mod.hpp, src/LuaType/LuaMod.cpp, src/LuaType/LuaUObject.cpp, src/Mod.cpp
This pull request contains several things that were needed for the update SplitscreenMod.
Added `ModRef.SetSharedVariable` and `ModRef.GetSharedVariable`.
Added `UObject.HasAnyInternalFlags`.
Added global table: `EInternalObjectFlags`.
You can now set an ObjectProperty value to `nil`. Previously such an action would be ignored.
When calling `IsValid()` on UObjects, whether the UObject is reachable is now taken into account.
The splitscreen mod now operates independently of the Lua state which means that hot-reloading shouldn't cause it to break.
=> Added a few Lua functions, fixed ObjectProperty unable to be set to nil.

Staging/Mods/shared/UEHelpers/UEHelpers.lua
The version number is intended to be increased whenever any changes are made to the module.
The intent is to allow scripts to verify that the currently installed module is of the correct version.
This could become important in the future if there eventually are breaking changes.
=> Added version tracking for the UEHelpers module.

Staging/UE4SS-settings.ini, include/SettingsManager.hpp, src/GUI/LiveView.cpp, src/SettingsManager.cpp
I also renamed "chunks" to "groups" to distance this mechanic from the chunks system in UE. While the two systems are similar, they are not the same and the live view isn't tied to the UE chunks system.
Also added 'LiveViewObjectsPerGroup' to the settings file to allow the user to control this number in case they experience lag.
=> Halved the number of objects per chunk in the live view.

src/LuaType/LuaFName.cpp, src/Mod.cpp
The second param is the 'EFindName' enum and is defaulted to EFindName::FNAME_Add to mimic the actual UE constructor.
This enum has also been exposed to Lua as a global variable called 'EFindName'.
=> The global Lua function 'FName' now has an optional second param.

Staging/API.txt, include/UE4SSProgram.hpp, src/Mod.cpp, src/UE4SSProgram.cpp
Requires https://github.com/Re-UE4SS/UEPseudo/pull/12
It returns a table of all directories & files within the root game directory.
The game name (i.e. FSD) gets replaced with the string "Game" to make it easier to refer to game files.
Usage:
local Dirs = IterateGameDirectories()
local Win64Dir = Dirs.Game.Binaries.Win64
local DirName = Win64Dir.__name
local AbsolutePath = Win64Dir.__absolute_path
=> Iterate game directories with Lua

Problems_For_3.0.txt, Staging/API.txt, Staging/UE4SS-settings.ini, include/GUI/LiveView.hpp, include/LuaType/LuaUObject.hpp, include/Mod.hpp, include/SettingsManager.hpp, src/GUI/GLFW3_OpenGL3.cpp, src/GUI/LiveView.cpp, src/LuaType/LuaUClass.cpp, src/LuaType/LuaUFunction.cpp, src/LuaType/LuaUObject.cpp, src/Mod.cpp, src/SettingsManager.cpp, src/UE4SSProgram.cpp
Added the `[Hooks]` section to the UE4SS-settings.ini file.
It has the following settings:
```
HookProcessInternal
HookProcessLocalScriptFunction
HookInitGameState
HookCallFunctionByNameWithArguments
HookBeginPlay
HookLocalPlayerExec
FExecVTableOffsetInLocalPlayer
```
IterateGameDirectories: No longer relies on `UKismetSystemLibrary::GetGameName()`.
This should make it work more consistently.
Added the following global Lua functions:
```
RegisterProcessConsoleExecPreHook
RegisterProcessConsoleExecPostHook
RegisterCallFunctionByNameWithArgumentsPreHook
RegisterCallFunctionByNameWithArgumentsPostHook
RegisterULocalPlayerExecPreHook
RegisterULocalPlayerExecPostHook
```
Added the Lua function `ProcessConsoleExec` to UObject.
Added the Lua functions `GetFunctionFlags` and `SetFunctionFlags` in …
=> Added more hooks & functions to Lua, and fixed some bugs.

StagingDev/API.txt, include/Mod.hpp, src/Mod.cpp, src/UE4SSProgram.cpp
Fixed UnregisterHook.
Expanded RegisterHook to work on BP functions where it previously only worked on native functions.
Added UnregisterCustomEvent.
Fixed bug that could cause hooked functions to not process the return value properly.
=> Changes & fixes to RegisterHook & added UnregisterCustomEvent.

src/main_ue4ss_rewritten.cpp
It's not clear to me what the purpose of this line is, but on Linux it will cause the game to appear to hang indefinitely without any user input in the console.
=> Remove stdin read which blocks until user input on Linux

cppsdk/CMakeLists.txt
This fixes the issue of mods having incorrect linkage when building using an `sln`
=> fix cppsdk linking incorrectly when building as sln

StagingDev/Mods/shared/Types.lua, include/SDKGenerator/Common.hpp, include/SDKGenerator/Generator.hpp, include/UE4SSProgram.hpp, src/GUI/Dumpers.cpp, src/SDKGenerator/Common.cpp, src/SDKGenerator/Generator.cpp, src/UE4SSProgram.cpp
https://user-images.githubusercontent.com/1144160/233905258-a7438c1b-8d67-4b99-8cf7-b19f883a2cd7.mp4
Adds Lua type definitions to be used by a [lua language server](https://marketplace.visualstudio.com/items?itemName=sumneko.lua).
[Annotation reference](https://github.com/LuaLS/lua-language-server/wiki/Annotations)
I decided to extend the existing CXXGenerator to generate Lua definitions as opposed to create an entirely new generator because they are more similar than they are different. I figured any quirks with how UE objects are accessed would be easier to keep updated if they weren't split between two different generators. The conditionals everywhere are undeniably ugly, however. Perhaps templates could be used to specify language at compile time? Or create intermediate structures to …
=> Add Lua type definition generator and definitions for UE4SS built-ins

include/Mod/CppMod.hpp, include/Mod/LuaMod.hpp, include/Mod/Mod.hpp
This fixes CppMod not freeing the library and being unable to hot reload.
=> Fix Mod destructors not getting called

CMakeLists.txt, include/GUI/GUI.hpp, include/GUI/GUITab.hpp, include/UE4SSProgram.hpp, src/GUI/GUI.cpp, src/GUI/GUITab.cpp, src/UE4SSProgram.cpp
I took a quick stab at #110. Some things to note:
1. I put `DebuggingGUI::m_tabs` behind a mutex to be safe, though this means tabs won't be able to add other tabs in the middle of a frame. Perhaps queuing new tabs up to add at the end of a frame would be better?
2. I moved mod setup to after console creation so the GUI would be available in the mod constructor. Assuming this doesn't break something else, this seems better than utilizing `on_program_start` as it is only run at UE4SS startup and doesn't run again for mod restarts.
3. I've included a hack that allows the mod .dll file to be swapped and reloaded, allowing hot reloading on my system using WINE. I thought very little about how sound it is and wouldn't actually include it, but it's nice for testing purposes.
I've got a test mod …
=> Expose ImGui tab creation to CppMods

Dependencies/Constructs/include/Constructs/Generator.hpp, Dependencies/Constructs/include/Constructs/Views/EnumerateView.hpp, include/LuaType/LuaUObject.hpp, src/GUI/BPMods.cpp, src/GUI/Dumpers.cpp, src/GUI/LiveView.cpp, src/LuaType/LuaCustomProperty.cpp, src/LuaType/LuaUEnum.cpp, src/LuaType/LuaUObject.cpp, src/LuaType/LuaUStruct.cpp, src/Mod/LuaMod.cpp, src/ObjectDumper/ObjectToString.cpp, src/SDKGenerator/Generator.cpp, src/SDKGenerator/JSONDumper.cpp, src/SDKGenerator/TMapOverrideGen.cpp, src/SDKGenerator/UEHeaderGenerator.cpp, src/UE4SSProgram.cpp, src/USMapGenerator/Generator.cpp
This patch removes the need for passing lambdas into `ForEach` functions in a lot of places, instead replacing the iterator producing functions with coroutines that yield the results.
This change allows for more effective work with any iterable by allowing to construct STL containers from them, use ranges on the iterables, etc.
Coroutines also allow for much faster iteration than the current method when compiled with clang.
=> Initial generators+views implementation

src/UE4SSProgram.cpp
It's not completely unique by any means but should in most cases make it obvious if a log is originating from a different version of a game.
=> Log game exe file path and size to help with identification

CMakeLists.txt
Also make the switch more idiomatic with CMake options instead of reading files.
=> Fix case preserving names switch

include/GUI/LiveView.hpp, src/GUI/LiveView.cpp
This allows searching for functions that have parameters with the specified property flags, for example, CPF_OutParm. By default, this option excludes the return parameter but it can be included by ticking a checkbox.
=> Added a new search option to the live view

src/USMapGenerator/Generator.cpp
Adds .usmap file dumping with 4-byte ASCII extension identifiers for decentralized extension development rather than using a fixed enum. Future pull requests can add new extensions to the dumper
=> usmap ext 2

include/UE4SSProgram.hpp, src/UE4SSProgram.cpp
This PR fixes cppmod restarting not calling initialization functions correctly, also prevents cppmods from being loaded if no cppsdk was found.
=> CppMods fixes

docs/lua-api/classes/uscriptstruct.md
The current explanation is misleading if you don't have any knowledge of the concept of Lua metafunctions. Hopefully I have explained this correctly with valid examples.
=> Update uscriptstruct with examples of index and newindex usage

include/Mod/LuaMod.hpp, src/Mod/LuaMod.cpp
current behavior is to infinitely grow the mod's stack until we write out of bounds on the heap.
note that `mod->lua().get_lua_state()`, `hook_lua->get_lua_state()` and `lua.get_lua_state()` are three different states.
verified no crashes on reload now with gflags +hpa and LUA_USE_APICHECK enabled
=> fixes for various unload & executeingamethread gc-related crashes

Dependencies/ImGuiColorTextEdit/TextEditor.cpp
Skipping the filter when empty causes console render time to remain constant regardless of length.
=> Fix always-active O(n) console log filter

Dependencies/Helpers/include/Helpers/String.hpp, include/LuaType/LuaUObject.hpp, src/LuaType/LuaUObject.cpp
Profiled 3k ufunction calls in a loop:
* 12800ms spent.
* 99% of that spent in FindObjects, fixed via GetFunctionByNameInChain
* 40ms spent allocating wstrings, fixed via introducing `to_const_wstring` pool
* 25ms spent in FindProperty, fixed via https://github.com/Re-UE4SS/UEPseudo/pull/44/commits/6e14bc4b0b5b0b08378df458609f4fd0e8d0b370
end result is 3k ufunction calls in <9ms on my machine
Testing performed was mostly running a mod on my current target that uses a variety of functionality, though I'm probably only accessing ~20 UFunctions and ~50 properties on 7 different classes of UObject.
=> Improve Lua UFunction call performance

include/Mod/CppMod.hpp, include/Mod/CppUserModBase.hpp, include/UE4SSProgram.hpp, src/Mod/CppMod.cpp, src/UE4SSProgram.cpp, src/main_ue4ss_rewritten.cpp
This is achieved by splitting UE4SSProgram constructor into an init function, and only initializing the bare minimum in the constructor. This allows for the constructor to be in DllMain and run our code before any game code actually runs.
CppMods also got a new `dll_load` event, which notifies them when any dll got loaded into the process, this allows for mods to monitor when a dll that they're interested in loaded, and act accordingly.
=> CppMods are now loaded earlier

include/GUI/LiveView.hpp, include/GUI/LiveView/Filter/DefaultObjectsOnly.hpp, include/GUI/LiveView/Filter/ExcludeClassName.hpp, include/GUI/LiveView/Filter/FunctionParamFlags.hpp, include/GUI/LiveView/Filter/HasProperty.hpp, include/GUI/LiveView/Filter/IncludeDefaultObjects.hpp, include/GUI/LiveView/Filter/InstancesOnly.hpp, include/GUI/LiveView/Filter/NonInstancesOnly.hpp, include/GUI/LiveView/Filter/SearchFilter.hpp, src/GUI/LiveView.cpp
Each "search option" is now referred to as a "filter". Each filter has its own file & class which keeps LiveView.cpp clean. Each filter can keep track of state but the state must be static as we're never instantiating any of these classes but this could be changed if needed.
To create a new filter:
1. Create <FilterName>.hpp in the same directory as this file.
2. Create a class that has either a 'pre_eval' or 'post_eval' function that returns true. 'pre_eval' is executed before the object name has been processed if a search is currently being done. 'post_eval' is executed after the object name has been processed.
3. The 'pre_eval'/'post_eval' function must return true if the object is to be filtered out, and otherwise false.
4. Open GUI/LiveView.cpp and find the 'SearchFilters' variable …
=> Reworked the LiveView search options system

assets/Mods/Keybinds/Scripts/main.lua, docs/feature-overview/dumpers.md
To avoid issues where you're playing the game and you accidentally hit the keybind (a mistake that is easily made with current defaults).
=> Change default keybinds for cxx/object dumpers

include/GUI/GUITab.hpp, include/Mod/CppMod.hpp, include/Mod/CppUserModBase.hpp, src/GUI/GUI.cpp, src/Mod/CppUserModBase.cpp
GUI tabs have been simplified both for use with mods and without mods.
Simply call `register_tab` in your mod constructor with a name and a render function.
The render function has this signature: `void(CppUserModBase*)`.
The `CppUserModBase*` param can be safely cast to your own mod class.
The param is nullptr if the tab wasn't created with the `register_tab` function.
The tab is automatically removed when your mod is unloaded.
Tabs can also be created with `UE4SSProgram::add_gui_tab` and in which case it requires that you construct a `GUI::GUITab` yourself and you also have to manually call `UE4SSProgram::remove_gui_tab` to remove the tab when your mod unloads.
=> Simplified GUI tabs

UE4SS/include/Mod/CppMod.hpp, UE4SS/include/Mod/CppUserModBase.hpp, UE4SS/include/Mod/LuaMod.hpp, UE4SS/src/Mod/CppMod.cpp, UE4SS/src/Mod/LuaMod.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
Also, Lua mods are now guaranteed to be uninstalled before C++ mods when mods are reinstalled/hot-reloaded.
=> Added 'on_lua_stop' to C++ mods

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
If provided, it will act as a post callback hook where out-params can be modified.
The return value can be modified by simply returning the new value.
If you don't return anything, the return value from the pre callback will be used unless that callback also didn't return anything, in which case the original UFunction return value will be used.
If you return something in this function, it will override any return value from the pre callback.
Note that for BP-only functions, both callback to RegisterHook act as a post callback.
=> Added an optional third param to the global Lua function RegisterHook

UE4SS/include/GUI/LiveView/Filter/HasPropertyType.hpp, UE4SS/src/GUI/LiveView.cpp, assets/Changelog.md
The type is case-senstivive, so 'arrayproperty' will not work but 'ArrayProperty' will.
It filters out any objects that doesn't contain a property of the specified type.
Very useful for locating functions that have specific types of properties for testing purposes.
=> Added 'Has Property Type' search filter to live view

deps/first/Constructs/include/Constructs/Annotated.hpp, deps/first/Constructs/include/Constructs/CompileTimeString.hpp
Annotated types allow for types to have comments at runtime. This is mostly useful for json to provide comments inside of the json file, but could have other applications as well.
The types are done using compile-time strings/arrays to improve developer experience when creating instances of annotated types.
=> Constructs: add annotated types

CMakeLists.txt
These fixes were the project to not link if actually built with CLion.
=> Made the CLion fixes optional

.github/workflows/experimental.yml
This is no longer needed with the new default proxy dll
=> Remove directx SDK download from experimental release action

cmake/CompilerOptions/msvc.cmake
Will be required for the upcoming SDK generator.
=> Added '/Zc:preprocessor' to MSVC builds

CMakeLists.txt, UE4SS/proxy_generator/CMakeLists.txt
Couple of changes required to build on Linux using clang.
Using [xwin](https://github.com/Jake-Shadle/xwin) to obtain Windows libraries and headers:
```bash
xwin splat --output xwin --include-debug-libs
XWIN="$(realpath xwin)"
export INCLUDE="$XWIN/crt/include;$XWIN/sdk/include/ucrt;$XWIN/sdk/include/um;$XWIN/sdk/include/shared"
export LIB="$XWIN/crt/lib/x86_64;$XWIN/sdk/lib/um/x86_64;$XWIN/sdk/lib/ucrt/x86_64"
cmake -B build -G Ninja \
-DCMAKE_C_COMPILER=clang-cl \
-DCMAKE_CXX_COMPILER=clang-cl \
-DCMAKE_MT=/usr/bin/llvm-mt \
-DCMAKE_ASM_MASM_COMPILER=/usr/bin/llvm-ml \
-DCMAKE_ASM_MASM_FLAGS=--m64 \
-DCMAKE_BUILD_TYPE=Game__Shipping__Win64 \
-DCMAKE_SYSTEM_NAME=Windows \
-DUE4SS_PROXY_PATH=/path/to/xinput1_3.dll
cmake --build build
```
=> Fix cross compiling using clang on Linux

docs/SUMMARY.md, docs/guides/creating-a-lua-mod.md
Add a basic tutorial how to create a Lua mod in UE4SS. 
The included example should be basic and generic enough to run on a number of supported games.
=> fix: add a basic Lua mod creation tutorial

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
The second function passed to 'RegisterHook' now takes an additional param after the first param if the function has a return value. The param contains the return value pointer and you can use ':get()' to retrieve the value and ':set(<new-value>)' to set it but the return value of the actual Lua function will take precedence over calling 'set'.
Example:
```lua
RegisterHook("/Script/Engine.Character:CanJumpInternal", function()
-- Some code.
end, function(ParamContext, ParamReturnValue)
-- This value will be the original return value in the case where the pre-hook didn't modify it.
-- It will be the modification done by the pre-hook otherwise.
print(string.format("Return Value: %s\n", ParamReturnValue:get()))
end)
```
=> Lua hooks (RegisterHook) can now access the original return value

UE4SS/src/Mod/LuaMod.cpp, assets/Mods/BPModLoaderMod/Scripts/main.lua, assets/Mods/ConsoleCommandsMod/Scripts/dump_object.lua, assets/Mods/ConsoleEnablerMod/Scripts/main.lua, assets/Mods/shared/UEHelpers/UEHelpers.lua, docs/SUMMARY.md, docs/lua-api/global-functions/fname.md, docs/lua-api/table-definitions/efindname.md
This function will return the FName if it exists, and otherwise it will create it.
The UE documentation for 'EFindName::FNAME_Add' doesn't seem to be correct. It says: "Find a name or add it if it doesn't exist.", however, if the name already exists, it will add a new name with a number suffixed to it like "_0". This new UEHelpers function doesn't have this functionality and instead will return the original name without any extra suffix.
Also updated the docs to correctly point out that FNAME_Add is the default for the FName constructor, not FNAME_Find. Also added EFindName to the docs.
=> Added UEHelpers.FindOrAddFName

assets/Changelog.md
@UE4SS Just to check, this is the correct thing that needs to be done right? I had a look at the build script and am slightly confused how it tells the difference between releasing experimental version and an entirely new version based on how the changelog is (before 3.0.0 it was 2.6.0 which wasn't a tag that existed, and the -e passed into the py script doesn't seem to do anything). I tried to ask the actual guy who wrote it (truman) but he won't answer so I just want to make sure, if you know.
=> Reset changelog for future experimental releases

.github/ISSUE_TEMPLATE/bug_report.md
It directs people to zip their Mods directory if they've installed any mods that didn't come directly from us.
=> Added mods directory zip as an explicit step to the bug report template

UE4SS/src/LuaType/LuaUObject.cpp
This fixes the FString setter from lua which added an additional `\0`
byte at the end with each assignment.
=> fix(UE4SS): fix lua FString setter

docs/lua-api/classes/tarray.md, docs/lua-api/classes/ufunction.md, docs/lua-api/classes/uobject.md, docs/lua-api/classes/uscriptstruct.md
Resolves #374 
- Clarified usage of `__index`, `__newindex`, `__call` in multiple classes, placing them in a separate Metamethods category.
- Added `__len` metamethod description for TArray.
- UFunction `__call`: mention return val and specify the need for a context parameter if not part of an object instance.
- UObject `__index`: added example of a UFunction call.
- UObject `type()`: clarify that `type(object)` is not equivalent.
- Minor edits (spelling)
For initial review.
=> Clarify Lua metamethod usage for some classes; Minor docs edits

deps/first/ASMHelper/include/ASMHelper/ASMHelper.hpp, deps/first/ASMHelper/src/ASMHelper.cpp, deps/third/CMakeLists.txt
This fixes #317
Depends on https://github.com/Re-UE4SS/UEPseudo/pull/76
=> Polyhook update

deps/first/Input/include/Input/Handler.hpp
Fixes modifier key input issue in issue #380 
Built with Game__Shipping__Win64, tested on Palworld/Hogwarts Legacy both fresh install and with existing 3.0.0 release (just overwriting ue4ss.dll)
=> Updated Input/Handler.hpp

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
See commit message: 79b328f47196c9092c07413b6a8454f5ba01f4ec
Fixes #396 and #365
See commit message: 79b328f47196c9092c07413b6a8454f5ba01f4ec
**Checklist**
Add any other context about the pull request here.
=> Fix bpmodloader conversion error

UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md
Fixes FText param handling in Hooks/etc.
Tested by using `RegisterHook` on a sample project, then reading the received FText value, as well as replacing the return value.
**Checklist**
=> fix: lua FText param handling

UE4SS/src/LuaLibrary.cpp, assets/Changelog.md, docs/lua-api.md, docs/lua-api/global-functions/print.md
`print` in Lua can now accept any type without throwing an error. Additionally, `print` can now accept varargs - any number (within reason ofc) of (possibly mixed) arguments, which will be printed out into the console with each argument separated by tab(s). This is basically vanilla Lua behavior for `print` on a terminal.
Print basically any type including UE4SS types, with varying amount of arguments, and also do mixed arguments.
P.S. Zero args print empty `[Lua] ` line, also similar to vanilla Lua behavior.
<details>
<summary>[ Script used for testing ]</summary>
```lua
local ksl = StaticFindObject("/Script/Engine.Default__KismetStringLibrary")
local act = FindFirstOf("Actor")
local inv = …
```
=> feat(lua): print now prints any value, accepts multiple params

UE4SS/include/LuaType/LuaFString.hpp, UE4SS/src/LuaType/LuaFString.cpp, UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md
This fixes some issues related to FString lifetime causing it to become
garbage data, FString should be stored by value instead.
Credits: @yangff
Please include a summary of the change and which issue is fixed. Include relevant motivation and context. List any dependencies that are required for this change.
Fixes #397
Tested on an Unreal 5.1 game with calling/hooking different functions returning FString, doing stuff on the stack and trying to read the value back.
**Checklist**
=> fix: make FString a local lua param

UE4SS/src/GUI/Console.cpp, UE4SS/src/GUI/GUI.cpp, UE4SS/src/GUI/LiveView.cpp, assets/Changelog.md
Was supposed to only fix the watches tab, but I guess other parts of the GUI needed some tiny bits of attention too.
<details>
<summary><b>Fixes general alignment issues in the Console, Live View, and Watches tabs.</b></summary>
- Removed the weird gap underneath the Console log output, seems that it used to be meant for something else, but for now should probably fill that gap.
- Fixed the bottom panel of the LiveView splitter panels getting cut and extending beyond the window (seen with font scaling >= 1.0). I think one time I wondered if I'm missing a property entry because it might be hidden away outside the window. 
- The bottom of the pane appears at around font scaling <= 0.7-ish though, so the spacing under the pane seem to vary depending on scaling. Fixed by using …
=> fix(GUI): fix some widget alignments and font scaling issues

UE4SS/src/GUI/LiveView.cpp, assets/Changelog.md
I logged this as a fix in the changelog because even though it's technically a new feature, it's much more likely to be seen as a bug by people.
See commit messages.
Partially fixes #418
I tested this by adding a watch to `CanJumpInternal` and ticking `Write to file` and proceeding to jump in the game and then confirming that `ue4ss_watch_Character.CanJumpInternal_.txt` existed in the `watches` directory.
**Checklist**
Add any other context about the pull request here.
=> Implemented "Write to file" for UFunction watches in the watches tab & fixed a crash on shutdown

UE4SS/include/SettingsManager.hpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, assets/UE4SS-settings.ini
We've had the ability to hook AActor::Tick for a while now, but we never actually made use of this hook.
If https://github.com/Re-UE4SS/UEPseudo/pull/83 is merged, then this won't come with any performance penalties unless a C++ mod decides that they want to register an AActor::Tick hook.
Together with #442, I created a C++ mod with a custom ACharacter class with a Tick function, and verified that the Tick function was being executed when `HookAActorTick` was set to 1.
**Checklist**
=> Added 'HookAActorTick' to UE4SS-settings.ini

UE4SS/include/Mod/LuaMod.hpp, UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md, docs/lua-api/global-functions/notifyonnewobject.md
The callback of `NotifyOnNewObject` can now optionally return true to unregister itself. Technically, this would probably be breaking as `return true` (specifically) in a `NotifyOnNewObject` callback will suddenly have a meaning, but I do not think anyone will do that (as there is no documentation that says to return something in there), much less think that it is not for "cancelling" the callback.
Any other value as return won't unregister the callback though, even if they coerce to true, only an explicit `true` as the first return value will work. This is to minimize the (low) possibility of the change to break things in case someone did return values from the callback.
I've done:
- Call sequence + cancel checks to:
- check if callbacks are still called the same sequence as they're …
=> feat(lua): allow NotifyOnNewObject callback to unregister itself

UE4SS/src/LuaType/LuaTArray.cpp, assets/Changelog.md
Fixes #435 (forked from it's original issue). The new array size is incorrectly computed in `TArray::prepare_to_handle` and targets a size that is 1 less than the intended array size. This causes it to not zero out and resize except for when you add _additional_ elements after it- this leaves a trail of zeroed out entries, with one "missing" because the size was off for each call.
Verified the following script reproduces the issue and outputs garbage for [4] and [5] the first time, and 0x0000 for [4] the second time ([5] still garbage).  Updated code and tested script to confirm both iterations output 0x0000 for [4] and [5]. Additionally stepped …
=> Fix off-by-one error in TArray::prepare_to_handle 

UE4SS/src/Mod/CppMod.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
This was done to fix PalServer not working properly after an update. The usage of 'SetDefaultDllDirectories' was there to allow C++ mods that have dynamic dependencies to store those dependencies right next to main.dll instead of in the Win64 directory.
This behavior remains intact, but we're using 'LoadLibraryEx' instead of 'LoadLibrary' to set the path specifically for main.dll instead of globally with 'SetDefaultDllDirectories'.
See #452 for discussion around this problem.
Fixes #452.
I made a C++ mod and a dependency with at least one export and dynamically linked that dependency with my C++ mod.
I then added both dlls (main.dll & dep.dll) to my UE4SS installation for …
=> Replaced usage of 'SetDefaultDllDirectories'

assets/Mods/BPModLoaderMod/Scripts/main.lua
This PR fixes a small error which prevented BPLoader from loading mods contained within subdirs of `LogicMods`.
Prior to this change, `LogicMods/Author-ModName/ModName.pak` would be _recognized_ by BPLoader but not actually loaded. If this file was moved into the top-level dir `LogicMods/ModName.pak`, it would then work.
=> Fix invalid BPLoader mod subdir behavior

tools/xmakescripts/build_configs.lua
Fixes UNICODE and _UNICODE macros not being exported correctly breaking the `TEXT` macro.
Compiling a mod that includes `UE4SSProgram.hpp`.
=> fix: UNICODE exports

UE4SS/proxy_generator/proxy/xmake.lua
The proxy target did not export any symbols, causing UE4SS to fail loading with "The application was unable to start correctly (0xc000007b)" when using the new xmake-built proxy (dwmapi.dll). 
~~Correcting the proxy build issue also fixed the OpenGL white screen issue in the debugging GUI.~~ ~~Possibly relevant to discussion in #344.~~ My local builds with this change seem to fix the OpenGL white screen issue, but the issue remains on Github runner-built releases.
Use new dwmapi.dll with UE4SS. Should load fine with the changes.
=> fix(proxy): fix proxy dll not exporting symbols

UE4SS/src/Mod/LuaMod.cpp
It seems that VS2019 should still be supported according to the readme. This should work around the issue with building with (some versions of?) VS2019, where [LuaMod.cpp#L2206](https://github.com/UE4SS-RE/RE-UE4SS/blob/73d337852d004f71bd1b5d24ad703263854e44e7/UE4SS/src/Mod/LuaMod.cpp#L2206) fails with "`error C3493: 'i' cannot be implicitly captured because no default capture mode has been specified`," which I assume is a MSVC quirk, as it doesn't make sense otherwise. Happened on a windows-2019 Github runner, and coincidentally on one other person too.
<details>
<summary>Testing</summary>
Test code:
```lua
ExecuteInGameThread(function()
local dirs = IterateGameDirectories()
for k, GameDirectory in pairs(dirs) do
print(("%s: %s [%s]"):format(k, GameDirectory.__name, …
```
=> fix: compilation quirk with vs2019

UE4SS/include/Mod/CppUserModBase.hpp, UE4SS/include/UE4SSProgram.hpp, UE4SS/src/Mod/CppUserModBase.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, deps/first/Input/include/Input/Handler.hpp, deps/first/Input/src/Handler.cpp
This only happened if the hot-reload feature was used to reload all mods.
This was fixed by introducing `CppUserModBase::register_keydown_event`.
It's identical to the one in UE4SSProgram, except it keeps track of which C++ mod registered the event so that it can be "unregistered" when the mod is reloaded.
Mods that continue to use the UE4SSProgram version will continue to have the same problem.
I created a C++ mod that registered a keybind with the new function that output something to the console, and verified that only one message in the console appeared after using the bind after spamming the "Restart All Mods" button.
**Checklist**
=> Fixed keybinds created from C++ mods executing multiple times

UE4SS/src/GUI/LiveView.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
This happened even if the user wasn't on the live view tab. It didn't happen if the GUI was turned off in the ini file.
Also fixed a bug where 'object_full_name.find(name_to_search_by)' would return 0 instead of npos if 'name_to_search_by' was an empty string.
Fixes #473 
**Checklist**
=> fix: Live View constantly searching

UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md
Fixes #474
With the following script, and also LineTraceMod.
```lua
function printf(...)
print(string.format(...))
end
function IterateTable(t)
for k,v in pairs(t) do
print(string.format("%s == %s\n", k, v))
end
end
RegisterKeyBind(Key.I, function()
local Math = StaticFindObject("/Script/Engine.Default__KismetMathLibrary")
local Val = Math:Add_IntInt(2, 3)
print(string.format("Val: %s\n", Val))
local class = StaticFindObject("/Script/Engine.Actor")
local gameplayStatics = StaticFindObject("/Script/Engine.Default__GameplayStatics")
local worldctx = FindFirstOf("GameInstance")
local results = {}
print("GetAllActorsOfClass() before\n")
gameplayStatics:GetAllActorsOfClass(worldctx, …
```
=> fix(Lua): Crash when calling functions taking Array<T> as an 'Out' param

UE4SS/include/Mod/CppMod.hpp, UE4SS/include/Mod/CppUserModBase.hpp, UE4SS/include/Mod/Mod.hpp, UE4SS/include/UE4SSProgram.hpp, UE4SS/src/Mod/CppMod.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, docs/guides/creating-gui-tabs-with-c++-mod.md
This only happens if the mod uses `UE4SS_ENABLE_IMGU`' macro in the constructor.
The purpose of this is to guarantee that imgui context has been set before a mod uses any imgui functions. Previously, we were assuming that the context would be set by the time the mod construct was called, however this was actually a race condition. It was possible for the mod constructor to be called before the UI code in UE4SS created the imgui context.
See #469
**Checklist**
=> fix(C++ Mods): Delayed mod constructor until imgui is initialized

.github/workflows/experimental.yml, .github/workflows/release.yml
Use GitHub PAT (personal access token) to avoid 'early EOF' errors in workflow runner. This essentially replaces the use of SSH in the workflows.
Resolves #437.
- Generate a PAT on the user that holds [UEPseudo](https://github.com/Re-UE4SS/UEPseudo), either a "fine-grained token" or a "classic token" (more on that below), under Settings, Developer Settings, Personal access tokens.
- Add the PAT to RE-UE4SS repository action secrets (under repo's Settings, Secrets and variables, Actions), with secret name being `UEPSEUDO_PAT`, and with the personal access token as the value.
Note: The SSH key is still used in other workflows other than experimental and release.
Personal access tokens can be either classic or fine-grained. __**Fine-grained tokens**__ allows for read-only access to private …
=> fix: use GitHub PAT to avoid 'early EOF' errors in workflow runner

assets/Changelog.md, deps/first/File/include/File/Enums.hpp, deps/first/File/src/FileType/WinFile.cpp
This fixes a problem with FileHandle::memory_map where it was impossible to successfully memory map a file if it was opened using File::open with any value other than OpenFor::Reading.
By creating a file (with `File::open`), and then calling `memory_map` on it.
**Checklist**
=> feat: Added File::OpenFor::ReadWrite

.github/workflows/experimental.yml, .github/workflows/release.yml
Adds github action caching to the release actions. Currently it only works for xmake dependency downloads, so cuts down about 30% of the build time. Could not get it to work for incremental compiling though (tried adding `--ccache=y` to build target command, and adding `build.cache` policy in `xmake.lua`).
Ran experimental action on branch a few times to check that the caching is being done properly.
**Checklist**
N/A
=> feat: build caching

UE4SS/src/USMapGenerator/Generator.cpp, assets/Changelog.md
mappings file now dumps to working dir instead of root dir
Ran mappings dumper with working dir both in root dir and in root/ue4ss folder
**Checklist**
=> fix: mappings file dump location

assets/Changelog.md, deps/first/File/src/FileType/WinFile.cpp
This made the move constructor useless if you memory mapped something because the destructor would always try to unmap which meant the map is no longer valid which meant it was impossible to pass around a memory map.
**Checklist**
=> fix(WinFile): File invalidation didn't take into account memory maps

UE4SS/include/GUI/GLFW3_OpenGL3.hpp, UE4SS/include/GUI/GUI.hpp, UE4SS/include/GUI/Windows.hpp, UE4SS/src/GUI/GLFW3_OpenGL3.cpp, UE4SS/src/GUI/GUI.cpp, UE4SS/src/GUI/Windows.cpp
Add imgui userdata for backend window intended to scale into use for injected window as well
Needs to be changed to save less often. Either on exit or if moved and every 5 seconds or similar prior to merging.
=> Update ImGui ini location; make os window position and size persistent across runs

UE4SS/src/CrashDumper.cpp
Fixes yet another missed case with #506 
It hasn't, I need someone to test it by forcecrashing the game to make it generate a dump report. Idk how to crash it to generate dmp report, I thought maybe something like dereferencing a null pointer might work but that just crashes with no report.
=> fix: crash dumps are sent to working directory

UE4SS/include/CrashDumper.hpp, UE4SS/src/CrashDumper.cpp, UE4SS/src/UE4SSProgram.cpp
Cleanup CrashDumper to not include Windows.h and not use polyhook in headers.
Compiling the project after the change.
=> chore: remove Windows.h from CrashDumper

tools/xmakescripts/plugins/ci/dump/modes.lua, tools/xmakescripts/plugins/ci/dump/targets.lua, tools/xmakescripts/plugins/ci/main.lua, tools/xmakescripts/plugins/ci/xmake.lua, xmake.lua
`xmake ci --dump=targets`
<details><summary>Expand to show result</summary>
```json
{"File":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\File\\File.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\File\\File.lib"},"DynamicOutput":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\DynamicOutput\\DynamicOutput.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\DynamicOutput\\DynamicOutput.lib"},"LuaRaw":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\LuaRaw\\LuaRaw.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\LuaRaw\\LuaRaw.lib"},"KismetDebuggerMod":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\KismetDebuggerMod\\KismetDebuggerMod.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game …
```
=> Add xmake ci --dump command

.github/workflows/experimental.yml, .github/workflows/release.yml
https://github.com/xmake-io/xmake/pull/4800
Need to bump xmake to the dev branch because that's where the fix landed. GitHub runners were updated to new toolsets and this is a result of that.
=> Bump CI xmake version to dev branch

deps/third-repo/packages/p/polyhook_2/CMakeLists.txt, tools/xmakescripts/rules/build_rules.lua
microsoft/STL#3824
microsoft/STL#4000
microsoft/STL#4339
Add escape hatch due to STL change resulting in issues with binary compatibility.
https://github.com/microsoft/STL/wiki/Changelog
"Fixed bugs:
Fixed mutex's constructor to be constexpr. #3824 #4000 #4339
Note: Programs that aren't following the documented restrictions on binary compatibility may encounter null dereferences in mutex machinery. You must follow this rule:
When you mix binaries built by different supported versions of the toolset, the Redistributable version must be at least as new as the latest toolset used by any app component.
You can define _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR as an escape hatch."**Description**
Tested on Wine where this issue originally caused hangs. …
=> STL updates Mutex Fix

UE4SS/xmake.lua
Fmt had a change that enabled unicode by default
https://github.com/fmtlib/fmt/commit/b7809f91e2cc42d3bb693e742a28815832c6cb89
xrepo followed up this change by adding v11.0 of the package to the xmake repository
https://github.com/xmake-io/xmake-repo/pull/4533
Proposing to lock the version prior to this unicode change since it causes build failures
```text
error: TokenParser.cpp
C:\hostedtoolcache\windows\xmake-global\.xmake\packages\f\fmt\11.0.0\ef30b2773db346bbb83a54df6d28dc26\include\fmt\base.h(457): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'
```
=> Lock fmt package version to 10.2.1

deps/first/File/include/File/Macros.hpp, deps/first/File/src/FileType/WinFile.cpp, deps/first/File/xmake.lua, deps/first/JSON/src/Number.cpp, deps/first/String/include/String/StringType.hpp, deps/first/String/xmake.lua, deps/first/xmake.lua
This PR just moves `StringType` from File to String.
Right now, CharType is set to `whcar_t`, for a verification build for Linux, one can try to build when it is set to `char16_t`.
It is not intended to solve the circlular dependency in this PR but we may someday as suggested by @localcc seperate Unreal module into Unreal and UnrealDef.
Once this is sovled, CharType should be set to `TCHAR` for normal build.
I think it's safe to say TCHAR will be UTF-16 at this point, if we want to support cases that TCHAR can be say... utf8/utf32.. then might need to wrap it with `to_string` or `to_wstring` based on platform/env.. or pull back the `to_system` macro for those cases..
I have not tested this change but cherrypick it from my current working branch as suggest by @narknon to allow this part to …
=> Port/strings Typedef

docs/installation-guide.md
Docs were showing UE4SS.dll appended on example paths which is incorrect. 
Loaded relative & absolute paths in override.txt.
**Checklist**
=> fix: override.txt docs incorrectly showing example paths

UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
This fixes `ModsFolderPath` in `UE4SS-settings.ini` being broken.
Move `Binaries/Win64/Mods` to ~~`Binaries/Mods`~~`Content/Paks/Mods`, and set `ModsFolderPath` to `../../Content/Paks/Mods`.
**Checklist**
=> fix: Mod directory being used before it's setup

.github/workflows/ue4ss-ci.yml
We don't want to have to wait the 20 ish minutes for the PR CI to do its checks when some files that do not affect the build changes.
For example, currently, if someone were to change the `assets/Changelog.md` in a PR, it would still run all of the build checks despite nothing that affects the build changing. The same goes with all other files in paths added. 
`assets/**` is included because the PR CI only builds `UE4SS.dll` and does not produce an experimental-like zip.
We'll see when this is merged! (change is too trivial to spend an hour setting up PR CI to work on fork for test)
=> PR CI: Ignore more paths that do not affect build

.github/workflows/msvc_build_ue4ss.yml, README.md, UE4SS/xmake.lua, tools/xmakescripts/rules/build_rules.lua, tools/xmakescripts/rules/rust_rules.lua, tools/xmakescripts/rules/version_rules.lua
Some build issues have been caused in the past and recently when the user does not meet the minimum build requirements. 
This PR aims to solve this by checking the Rust and MSVC minimum requirements, and, if they are not met, error out on config, not allowing build to begin in the first place. xmake already uses `set_xmakever` which works fine for minimum version.
In the case of #615, the user is using the current preview version which has a higher MSVC version, and causes the build to fail. This PR additionally prints a warning (and continues build) if they are using this current MSVC version. We should keep an eye on this version and fix the issue at the root or see if this is just a compiler bug, but in either case, eventually remove this temporary measure.
The PR also …
=> Raise error or warning depending on installed rust/msvc versions

UE4SS/src/SDKGenerator/UEHeaderGenerator.cpp, assets/Changelog.md
`this->someproperty->SetupAttachment(someparent)` implementations in constructors randomly change order between sessions, and as a consequence, makes diffs more difficult to read (or manually fix them to not mess up the diffs). 
This PR simply sorts them by someproperty. There is no observed performance impact.
1. Run game
2. Make dump (rename folder to not be overwritten)
3. Restart game
4. Make another dump
5. Check in winmerge that all files are identical
**Checklist**
=> UHT - Fix SetupAttachment implementations randomly changing order

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
The `RegisterProcessConsoleExecPostHook` function was broken and unusable.
This was because we were passing the wrong number of params to `call_function` causing it to attempt to call a value that wasn't a function.
Use `RegisterProcessConsoleExecPostHook` in a Lua script, enable the console enabler mod and type anything in the console and there's no longer an error outputted to the UE4SS console.
**Checklist**
=> fix: RegisterProcessConsoleExecPostHook not passing the correct number of params to call_function

deps/first/JSON/include/JSON/String.hpp, deps/first/LuaMadeSimple/include/LuaMadeSimple/LuaMadeSimple.hpp, deps/first/LuaMadeSimple/src/LuaMadeSimple.cpp
Fixes clang compilation
Compiled on several configurations and used on games of different versions
=> Fix clang compilation

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md, assets/Mods/shared/Types.lua, docs/SUMMARY.md, docs/lua-api.md, docs/lua-api/global-functions/createinvalidobject.md
Resolves #652
**Testing**
Built UE4SS and deployed in Abiotic Factor.
Tested with Lua code:
```lua
local blankObject = CreateBlankObject()
print("blankObject varibale type: " .. type(blankObject))
if blankObject then
print("blankObject userdata type: " .. blankObject:type())
print("blankObject IsValid:" .. tostring(blankObject:IsValid()))
end
```
Result:  
```
[12:40:32.1231285] [Lua] blankObject varibale type: userdata
[12:40:32.1231360] [Lua] blankObject userdata type: UObject
[12:40:32.1231428] [Lua] blankObject IsValid:false
```
**Additional**
Fixed `FindFirstOf` return type annotation in `Types.lua`
**Documentation**
All changes documented in `Changelog.md` and created a new docs page for `CreateBlankObject`.
=> Added global lua function CreateInvalidObject (#652)

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md, assets/Mods/shared/Types.lua
Added  GenerateLuaTypes like described in #625.
Additionally added dumpers functions to Types.lua.
Built UE4SS and tested in Abiotic Factor. The function works and does exactly the same as the button in the GUI.
resolve #625
=> Implement global Lua function GenerateLuaTypes (#625)

assets/Changelog.md, assets/Mods/shared/Types.lua, assets/Mods/shared/UEHelpers/UEHelpers.lua, docs/guides/using-custom-lua-bindings.md
UEHelpers changes:
- Bumped version to 3. (I don't think it's really necessary since no breaking changes were made. Also should it be v3 or something like 2.1 etc.?)
- Added a local RemoteObject class that allows to create placeholder objects with a IsValid function
- Reworked UEHelpers to ensure that all functions never return nil but an object with a IsValid function
- Added functions GetEngine(), GetGameViewportClient()
- Reworked GetWorld() to get the current UWorld instance from UGameViewportClient. (PlayerController can be invalid, UGameViewportClient always exist)
- Rework GetWorldContextObject() to return UGameViewportClient. (Same as for GetWorld(). In UE any UObject that has the GetWorld() function is a valid WorldContext)
- Removed duplicate function …
=> UEHelpers improvements. Ensure that all functions return a RemoteObject and not nil. Add more functions, Rework some

.github/workflows/experimental.yml
Currently no changes in "assets" directory trigger an experimental release.  
I think it should happen since changes on Lua mods or in the `UE4SS-settings.ini` can be important.
=> ops: Trigger the Experimental release action for every Lua mod or ini change

UE4SS/include/SettingsManager.hpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, assets/UE4SS-settings.ini
Requires Re-UE4SS/UEPseudo#101
=> Housekeeping for adding basic dynamic dev/debug built game support

assets/Changelog.md, assets/Mods/shared/UEHelpers/UEHelpers.lua
UEHelpers rework goes in the third round with new experience, now testing it on a dedicated game server.
On a server first player controller instance appears only once a player has joined the server.  
Therefore, `GetPlayerController` returns an invalid object, as do `GetWorld` and `GetWorldContextObject`, which were dependent on the player controller.  
I immediately run into the problem that I need a valid WorldContext/World while there are no players on the server.  
I've changed the `GetWorld` to get the UWorld from the UGameInstance which always exist and returns the same UWorld player controller, but I left GetPlayerController code as fallback, in case a UGameInstance couldn't be found.  
The `GetWorldContextObject` now returns `GetWorld`.  
I will port some of my mods to make them …
=> UEHelpers Improvements for Dedicated Servers

.github/workflows/pushdocs.yml, assets/Changelog.md, docs-export/book.toml, docs-export/export.py
Add github alerts pre-processor which allows markdown such as [!IMPORTANT] and [!WARNING] to work in mdbook. 
README in docs currently not supporting this so is a bit difficult to read.
Tested changes on own fork of repo.
**Checklist**
=> Add github alerts pre-processor to mdbook

assets/Changelog.md, assets/Mods/ConsoleEnablerMod/Scripts/main.lua
- Check if ~ (Tilde) and F10 already exist as ConsoleKeys, if not add them at the end of the array
- Add some missing IsValid checks
- Removed obsolete parameters from callbacks and function calls
I don't know the reasons for the structure of the mod, but I couldn't find any harm in my improvements.  
Originally the mod overwrites the first hotkey for the console with **F10**, if the game has default settings that allows you to open the console, it would overwrite the default key.  
Also the most universal key to open a console on English keyboard layouts is **~** (tilde).  
My changes add **~** in addition to **F10**, check if hotkeys are already set, if not the mod expands the ConsoleKeys array and adds **~** and **F10** as additional options to open the console. Not only does it allow …
=> ConsoleEnablerMod overhaul

README.md, UE4SS/xmake.lua, deps/first/xmake.lua, deps/third-repo/packages/p/polyhook_2/CMakeLists.txt, deps/third-repo/packages/p/polyhook_2/xmake.lua, tools/xmakescripts/rules/version_rules.lua, xmake.lua
Changes to enable cross-compilation with [msvc-wine](https://github.com/mstorsjo/msvc-wine).
Follow the build instructions, which can be found in README.md included in this pull request.
**Checklist**
=> Cross-compile patch & build instructions

UE4SS/src/UE4SSProgram.cpp
FAssetData isn't used for core functionality and crashing here makes it harder to debug the root cause.  Requires Re-UE4SS/UEPseudo#102
=> Update warning message for FAssetData when loading all assets

UE4SS/include/LuaType/LuaUObject.hpp, UE4SS/src/GUI/ConsoleOutputDevice.cpp, UE4SS/src/LuaType/LuaUObject.cpp, UE4SS/src/Mod/LuaMod.cpp, UE4SS/src/UE4SSProgram.cpp
This PR makes various improvements to error messages.
Before
After
=> Better error messages

.github/workflows/experimental.yml
This PR makes a change to the experimental github action.
Instead of publishing all builds to https://github.com/UE4SS-RE/RE-UE4SS/releases/tag/experimental for archival/testing purposes, we now also publish the latest build to https://github.com/UE4SS-RE/RE-UE4SS/releases/tag/experimental-latest and this tag will always only have one asset, the latest build.
The benefit of this is that we can link to this new release page and users don't have to skim through hundreds of assets to find the latest build.
=> Added new tag for latest experimental build

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md, docs/lua-api/global-functions/findobject.md
Fixes FindObject not working with a UClass as the provided outer, previously failed with "No overload found for function 'FindObject'.".
Slightly improves documentation for FindObject and provides more examples.
Tested and works just fine to find objects which have a UClass as their outer.
=> Fix FindObject not working when specifying UClass outer

cppmods/KismetDebuggerMod/include/KismetDebugger.hpp, cppmods/KismetDebuggerMod/src/KismetDebugger.cpp
Update KismetDebuggerMod to use new global GNatives
=> Update KismetDebuggerMod to use new global GNatives

UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md
UFunction parameters that has type `TArray<...>&` discards the value passed from Lua for it, making the UFunction receive an empty array, or shifts the argument list and messes up parameter ordering.
`/Script/Engine.KismetStringLibrary:CullArray` and `/Script/UMG.WidgetBlueprintLibrary:GetAllWidgetsOfClass` are used to check if the parameters were passed correctly, by hooking into them and calling them from Lua.
<details>
<summary>Testing</summary>
Test code:
```lua
-- int32 CullArray(FString SourceString, TArray<FString>& inArray)
RegisterHook("/Script/Engine.KismetStringLibrary:CullArray", function (Context, SourceString, InArray)
print(">> CullArray call")
local str = SourceString:get()
print(("String: '%s'"):format(str:ToString()))
local arr = InArray:get()
print(("Array: __len %d, …
```
=> Lua: fix non-const TArray outparams being skipped in UFunction property pushers

assets/Changelog.md, assets/Mods/BPModLoaderMod/Scripts/main.lua
- Removed `ExecuteInGameThread` call from the `LoadMod` function.
- Ensured that `LoadMods` is always called in a game thread instead.
- Added `error` messages in case the `World` is **nil** in either the  `LoadMods` or `LoadMod` function.
According to the current mod logic with the new UEHelpers v3, the parameter `World` shouldn't be `nil` in either `LoadMods` or `LoadMod`. It can be an invalid UObject, but never `nil`. Therefore, if it should happen, we should assume that it is an error in  BPModLoaderMod's code.
Tested in Palworld v0.4.12 with [Mod Config Menu (UI)](https://www.nexusmods.com/palworld/mods/577) and [Basic MiniMap](https://www.nexusmods.com/palworld/mods/146) mods.
Here is a snippet from the log file without timestamps for better visibility:
```
Starting Lua mod …
```
=> BPModLoaderMod: Fix problem with out-of-scope variables in async call and ensure that LoadMods is always called in a game thread

UE4SS/include/SettingsManager.hpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
This PR adds a UGameViewportClient::Tick hook.
It currently doesn't register any hooks for this function, it just brings the ability to do so in the future.
**Checklist**
=> Added hook for UGameViewportClient::Tick

UE4SS/include/GUI/GUI.hpp, UE4SS/include/SettingsManager.hpp, UE4SS/include/UE4SSProgram.hpp, UE4SS/src/GUI/GLFW3_OpenGL3.cpp, UE4SS/src/GUI/GUI.cpp, UE4SS/src/GUI/Windows.cpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, assets/UE4SS-settings.ini
This PR adds an option to render the GUI in the game thread.
The default is still to render in its own GUI thread.
To turn on game thread rendering, set `RenderMode` in UE4SS-settings.ini to `GameViewportClientTick` in the `[Debug]` section.
Fixes #764 
With RenderMode set to `GameViewportClientTick`, start the game, make sure the GUI opens, and use CTRL + O to close it and again to open it.
Repeat with `RenderMode` set to `ExternalThread`.
**Checklist**
This needs to be tested for a bunch of games, and ideally by more than one person.
=> Option for rendering GUI in the game thread

UE4SS/include/Mod/LuaMod.hpp, UE4SS/include/SettingsManager.hpp, UE4SS/src/Mod/LuaMod.cpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
This PR adds hooks accessible via both Lua and C++ for `AActor::EndPlay`, in the same way that we have `AActor::BeginPlay`.
Make a Lua mod, register an EndPlay hook that prints the object name.
Start a game, load some save files, and quit.
Open UE4SS.log and make sure the output is correct.
**Checklist**
This may not be merged until #768 is merged.
If #768 doesn't get merged, this PR must be rebased onto main.
=> Added C++/Lua hooks for AActor::Endplay

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
There were mistakes in the code processing Lua pre-hooks for LoadMap, this PR fixes those mistakes.
By using `RegisterLoadMapPreHook` and verifying that it works.
**Checklist**
Wait for #768, #769, and #771, or rebase/cherry-pick before merging.
=> Fixed crash when using RegisterLoadMapPreHook from Lua

UE4SS/proxy_generator/exports/_dummy.exports, UE4SS/proxy_generator/exports/dwmapi.exports, UE4SS/proxy_generator/exports/xinput1_3.exports, UE4SS/proxy_generator/main.cpp, UE4SS/proxy_generator/xmake.lua
proxy_generator now generates an .exports file that it can reuse later, in place of dumping exports from system provided DLL. This avoids using the export arrangement from the GitHub runner's dwmapi DLL (from Windows Server 20xx) that reportedly breaks OpenGL graphics mode for the GUI console, and maybe breaks more things than that.
The .exports files are initially generated under the `Intermediate` directory (build log will print out the output path during proxy_generator run). These files are then pushed into the repository under `UE4SS/proxy_generator/exports`, so that for the next build, proxy_generator can use those exports. The .exports files can also be hand-made from `dumpbin.exe /EXPORTS` output, keeping in mind that the first line being in the form `Path: <path/to/orig.dll>` and …
=> Reuse exports for proxy dll generation

UE4SS/src/GUI/GLFW3_OpenGL3.cpp, assets/Changelog.md
This fixes the GUI not closing when CTRL + O is hit.
Hit CTRL + O a bunch and verify that only one window ever exists.
**Checklist**
=> Added missing glfw cleanup calls

UE4SS/include/LuaType/LuaTMap.hpp, UE4SS/include/LuaType/LuaUObject.hpp, UE4SS/src/LuaType/LuaTMap.cpp, UE4SS/src/LuaType/LuaUObject.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, assets/Mods/shared/Types.lua, docs/SUMMARY.md, docs/lua-api/classes/tmap.md
Adds `TMap` support to lua.
Tested by running a sample project in UE 5.3.2 and calling every function added.
**Checklist**
=> feat: add TMap implementation to lua

assets/Changelog.md, assets/Mods/shared/Types.lua, docs/lua-api/global-functions/ftext.md
I've noticed that the example of the use of `FText` object in `FText` function documentation was wrong, and the description overall is weirdly worded ("FText representation").  
I fixed the example code and improved the description to make it easier to understand what the function does.  
At the same time `FText` function was missing in the `Types.lua`.
=> Add FText function description to Types.lua and rewrite description in Docs

UE4SS/include/GUI/GUI.hpp, UE4SS/include/SettingsManager.hpp, UE4SS/include/UE4SSProgram.hpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, assets/UE4SS-settings.ini
Similar to #768 where `GameViewportClientTick` was added as a new `RenderMode` for the GUI Tool, I've added `EngineTick`.
Additionally, I had to add `HookEngineTick` setting, as it wasn't a thing yet.  
I put `EngineTick` everywhere in front of `GameViewportClientTick` because I think it's more important. GameViewportClient doesn't exist on servers and with Engine::Tick implementation the hook might be obsolete in the future.
**How it was tested**
After setting `RenderMode = EngineTick`, I attached the debugger to the game at the start and made sure that `Engine::Tick` is used instead of `GameViewportClient::Tick`.  
Then I played around in the Live View like before and it worked well. At least as good as it usually works.
Additionally, I tested it in Dedicated Server and …
=> Add HookEngineTick setting and EngineTick as GUI RenderMode

UE4SS/include/Mod/LuaMod.hpp, UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
This PR improved the performance of script hooks.
We were calling `GetFullName` every time `ProcessLocalScriptFunction` (4.22+) or `ProcessInternal` (<4.22) was called.
This is an expensive operation and should be avoided whenever possible.
This PR gets rid of this call in favor of comparing the FName of each outer of the function.
I did a very basic script hook with `RegisterHook` in Lua.
Please do some testing to make sure this PR doesn't break stuff.
**Checklist**
=> Performance improvements for script hooks

assets/Changelog.md, assets/CustomGameConfigs/Lies of P/UE4SS-settings.ini, assets/CustomGameConfigs/Lies of P/UE4SS_Signatures/FText_Constructor.lua, assets/CustomGameConfigs/Lies of P/UE4SS_Signatures/StaticConstructObject.lua
Patternsleuth detects the game as UE 4.26 while it's actually 4.27.  
StaticConstructObject doesn't match and while FText constructor works, it finds multiple addresses in some versions of the game.  
These changes solve these problems.
=> Custom game configurations for Lies of P

assets/Mods/BPModLoaderMod/Scripts/main.lua
In #752 I added an error message for the case that the World parameter passed to functions `LoadMod` and `LoadMods` is `nil`, which technically should never happen.  
It looks like in `LoadMods` it's only partially true.  
At the end of the script, the mod tries to execute `LoadMods` as soon as possible, by finding any AActor and using its UWorld.
```lua
ExecuteInGameThread(function()
local ExistingActor = FindFirstOf("Actor")
if ExistingActor:IsValid() then
LoadMods(ExistingActor:GetWorld())
end
end)
```
While I'm unsure if it would be better or easier just to get the current World with `UEHelpers.GetWorld()`, I have seen that at the time of loading and running the mod in some games `ExistingActor:GetWorld()` returns `nil`.  
I have no idea how it could be possible that …
=> BPModLoaderMod: Replace error with a warning message in the LoadMods function

UE4SS/src/LuaType/LuaAActor.cpp, assets/Changelog.md, docs/lua-api/classes/aactor.md
- Changed Lua functions `GetWorld()` and `GetLevel()` from `AActor` class to always return an `UObject`. (Previously they would return a `nil` instead.)
- Updated AActor documentation to match changes
- Added the changes to the `Changelog.md`
Added few log outputs to the `BPModLoaderMod` mod, which runs at the start of the game and finds an AActor which doesn't belong to a World or Level.  
Tested in game: **Avowed**
Code:  
```lua
ExecuteInGameThread(function()
local ExistingActor = FindFirstOf("Actor")
if ExistingActor:IsValid() then
local world = ExistingActor:GetWorld()
Log(string.format("GetWorld: %s\n", type(world)))
Log(string.format("GetWorld type: %s\n", world:type()))
Log(string.format("GetWorld:IsValid: %s\n", …
```
=> Change Lua `AActor` class functions `GetWorld()` and `GetLevel()` to return an invalid `UObject` instead of `nil`

UE4SS/proxy_generator/main.cpp
Fixes "fatal error LNK1121: duplicate ordinal number '1'" when building the proxy, due to undefined behavior of `ordinal` variable if not set nor initialized.
A user that had above fatal error on build has reported that the proxy has succeeded building after adding the change.
=> Fix proxy_generator proxy being unbuildable due to uninitialized variable

UE4SS/src/SDKGenerator/Generator.cpp, assets/Changelog.md, assets/Mods/shared/Types.lua
This PR ensures that types that do not actually exist in the Lua context as global variables are made local to the definition files only. This prevents cluttering of the autocomplete suggestions with numerous unusable variables.
Also did a few fixes and cleanup, refer to individual commit messages for more information.
<details>
<summary>Before</summary>
No warnings on inexistent global variables, suggestions are cluttered with types
Types are generated as globals
</details>
<details>
<summary>After</summary>
Types that are not global variables are properly labeled as warnings now, and suggestions are decluttered and easier to use
Generated types are now local-scoped
</details>
=> General improvements to Types.lua and generated Lua type definition files

assets/Changelog.md, assets/Mods/shared/Types.lua
Adds the missing, but documented, `UStruct` and `UClass` to Lua type definitions.
=> Add Lua type definitions for UStruct and UClass

UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md
Fixes `push_strproperty` pulling the wrong value in the stack because it did not respect `params.stored_at_index`, oftentimes appearing as the error: `Error: [push_strproperty] StrProperty can only be set to a string or FString` especially when being used in e.g. structs, a Lua table passed to a function or set as property.
<details>
<summary>Testing</summary>
Test code:
```lua
local engine = FindFirstOf("Engine")
local ksl = StaticFindObject("/Script/Engine.Default__KismetSystemLibrary")
---- Setting FString property in struct
--[[
struct FDirectoryPath
FString Path;
class UEngine
FDirectoryPath GameScreenshotSaveDirectory;
--]]
do
print("BEFORE", engine.GameScreenshotSaveDirectory.Path:ToString())
engine.GameScreenshotSaveDirectory.Path = "modified string 1"
print("AFTER 1", …
```
=> fix(lua): push_strproperty should use stored_at_index

UE4SS/src/Signatures.cpp, assets/Changelog.md, docs/guides/fixing-compatibility-problems.md
This change requires changes in the Unreal deps as well for this override to function.
Added ability to use a lua script to override ProcessLocalScriptFunction
- Potentially could be added to [this page](https://docs.ue4ss.com/guides/fixing-compatibility-problems.html)
- Created the file ProcessLocalScriptFunction.lua in ue4ss\UE4SS_Signatures which successfully overrides the built-in method.
- Removed the ProcessLocalScriptFunction.lua from that same directory and it successfully uses the built-in method.
**Checklist**
=> Added ProcessLocalScriptFunction Override functionality

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/docs_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
- Added new docs report & feature request issue templates
- Bug report and PR templates updated to put instructions into markdown comments so they don't need to be manually deleted (or left in which reads badly)
- Templates are auto-labelled on what they are
It hasn't aside from checking the markdown is valid with preview mode and checking with the docs that the metadata is valid (e.g. labels with spaces in working as they are)
**Checklist**
N/A
=> Update issue templates

UE4SS/include/Mod/LuaMod.hpp, UE4SS/src/Mod/LuaMod.cpp
Removed 'LuaCallbackData' in favor of 'LuaCallbackDataNoRef'
This was done by removing 'LuaCallbackData' and renaming 'LuaCallbackDataNoRef' to 'LuaCallbackData'.
The reason: Storing references in types that are meant to be put inside a container causes problems because you can't copy or delete them.
This PR was planned, as can be seen by the removed comment in LuaMod.hpp.
This PR is also required for a later PR that will move a lot of stuff from `LuaMod::global_uninstall` to `LuaMod::uninstall` to allow reloading one mod at a time.
=> chore(Lua): Removed 'LuaCallbackData' in favor of 'LuaCallbackDataNoRef'

docs/lua-api/global-functions/notifyonnewobject.md
The callback parameter was listed as the non-callback return value.
=> fix(docs): Incorrect label for NotifyOnNewObject callback params

README.md
Despite it being mentioned to use the non-dev and non-experimental version of UE4SS in the README, some end user still end up downloading the experimental version due to it being the very first thing they see on the linked release page, which may lead the mods that are expecting the stable version to have issues.
This at least helps elevate that. 
https://github.com/UE4SS-RE/RE-UE4SS/blob/8526b3bce9fc31edbe77056aee912bbd45c86034/README.md?plain=1#L24-L26
=> Link to latest stable release instead of pre-release in README

UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
Fixes #827 
See test case in #827.
**Checklist**
=> fix: RegisterHook/UnregisterHook not working properly with functions with spaces in their name

UE4SS/include/UE4SSProgram.hpp, UE4SS/src/Mod/LuaMod.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md
This PR introduces backend changes to allow Lua mods to be uninstalled one-by-one instead of requiring all mods to be uninstalled at the same time.
It's exposed via `LuaMod::uninstall` which clears the mod out of the global state, and `UE4SSProgram::untrack_mod` which deletes the mod and this must be called after `LuaMod::uninstall`.
**Checklist**
=> feat(Lua): Backend support uninstalling Lua mods one at a time

assets/Mods/shared/UEHelpers/UEHelpers.lua
I found an embarrassing error that I didn't test properly.  
`FHitResult` is a struct and has no `IsValid()` function.
**Changes**
- Removed HitResult:IsValid() check. It's a struct and has no such function.
- Changed the description of GetActorFromHitResult to be slightly more accurate, as it doesn't just deal with the difference between UE4 and UE5
- Removed `---@type AActor` annotation from `return CreateInvalidObject()`. It returns an UObject, which is a valid return type for GetActorFromHitResult.
Tested in my Line Trace mod.
=> UEHelpers: Fix GetActorFromHitResult and refactor it a little

docs-repo-template/gen-ps-games.py, docs/SUMMARY.md, docs/patternsleuth-games.md
Rename patternsleuth-games.md as old name (patternsleuth_supported_games.md) suggests it contains supported games. I know this is a breaking change, but the link exists for such a short time that it hardly matters, and better to do this now than later.
Add the python script that generates the file into the repo for future reference. Is in docs-repo-template due to that being the place where docs are built - if this page is automagically generated in the future, this is where the script would go.
=> chore(docs): Rename patternsleuth-games.md

UE4SS/include/LuaType/LuaUObject.hpp, UE4SS/src/LuaType/LuaFWeakObjectPtr.cpp, UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md, docs/lua-api/classes/fweakobjectptr.md, docs/lua-api/classes/localunrealparam.md, docs/lua-api/classes/remoteunrealparam.md
For whatever reason, `FWeakObjectPtr` uses `get` and `LocalUnrealParam` and `RemoteUnrealParam` uses `Get`.
This PR makes both variants available for all three types.
**Checklist**
=> fix(Lua): Types with 'get' functions now also have 'Get' and vice versa

assets/Mods/ConsoleEnablerMod/Scripts/main.lua
In 99.999% cases we only need to create console object once since it is also a singleton (on a singleton) and after that, the OnObjectConstrcuted event has no purpose for us.
I replaced the construct object hook with a native ufunction hook we can unhook from after we are done, as well as added a check for an imaginary case of dynamicviewport in case we somehow need to re-create the console over and over (I yet to ever meet a single UE game that dynamically juggles viewports).
We cant really get rid of a hook since there is no real 100% guarantee viewport instance is valid once we are loaded with UE4SS (even though this was the case on every test game I tried)
=> Make hook non-persistent for console enabler

assets/Changelog.md, deps/first/Helpers/include/Helpers/String.hpp
This PR enhances the string and path conversion utilities in the Helpers library with proper UTF-8 and UTF-16 support. The main improvements include rewriting the path conversion logic to handle Unicode correctly and adding several new utility functions for common string/path operations.
The key motivation is to ensure consistent and correct handling of Unicode paths across different platforms.
Necessary to be merged prior to #884
Conversion tests/tested with updated lua system.
**Checklist**
Breaking Change: The to_charT_string_path() function now returns UTF-8 encoded strings when the target type is char, instead of using locale-dependent encoding. This ensures consistent behavior across platforms …
=> Improve path conversions and add new string utilities

UE4SS/include/Mod/LuaMod.hpp, UE4SS/include/Mod/Mod.hpp, UE4SS/src/LuaLibrary.cpp, UE4SS/src/Mod/LuaMod.cpp, assets/Changelog.md
Adds a custom Lua module loader to handle Unicode paths and improves error handling during Lua mod loading. This change also introduces utility functions for safe string conversion and path encoding, ensuring proper handling of non-ASCII characters in Lua scripts and paths. It also fixes some error handling issues in `IterateGameDirectories` and `CreateLogicModsDirectory` lua functions also related to ASCII handling.
#335; #495
Running default mods on games with/without unicode and loading logic mods.
**Checklist**
=> fix(lua): improves Lua mod loading and path handling

UE4SS/src/Mod/LuaMod.cpp
Fixes an issue with the scripts folder of a Lua mod not being included in the package path.
This caused `require()` to always need the scripts folder to be included (e.g. `require("Scripts.myScript")` instead of just `require("myScript")`)
Fixes [the issue discussed on Discord](https://discord.com/channels/1148976194050605066/1148977475234316339/1385422612175261756), which was introduced in [this commit](https://github.com/UE4SS-RE/RE-UE4SS/commit/b72dfae17ec0197d67387b9ddbdb4b3c0897e045).
The scripts folder of Lua mods is now included in the package path and `require("myScript")` works properly.
=> Fix package path not including the scripts folder

UE4SS/src/Mod/LuaMod.cpp
Fixes an issue with some of the hook callbacks not being wrapped in a TRY block, thus not catching exceptions.
The callbacks now display errors properly and no longer crash the game completely.
=> Fix certain callbacks not catching exceptions

UE4SS/src/GUI/LiveView.cpp, assets/Changelog.md
Adds ability to expand StructProperty and ArrayProperty nodes within LiveView
Expanding `ScriptStruct /Script/CoreUObject.Transform` Struct Properties
Expanding `Class /Script/Engine.ActorComponent` UCSModifiedProperties Property
**Checklist**
=> Expandable struct and array properties

UE4SS/src/GUI/UFunctionCallerWidget.cpp
This PR fixes ImGui ID conflict warnings that occur when multiple functions have the same name in the live view function caller widget. The issue was that ImGui uses the selectable label as an identifier, so duplicate function names would create duplicate IDs. 
The fix appends a unique index to each selectable using ImGui's "##" separator convention, which creates unique IDs without changing the displayed text
1. Open the live view and select an object that has multiple functions with the same name (e.g., ExecuteUbergraph)
2. Open the function caller widget for that object
3. Verify that:
- All functions are displayed correctly with their original names
- No ImGui ID conflict warning popups …
=> fix(liveview): add unique IDs to function selectables in function caller

assets/Changelog.md, assets/Mods/shared/UEHelpers/UEHelpers.lua
This is inconsistent with the rest of UEHelpers which is supposed to never cause an error, it returns CreateInvalidObject instead.
**Checklist**
=> fix(UEHelpers): CacheDefaultObject erroring out instead of returning an invalid object

UE4SS/include/LuaType/LuaUObject.hpp, UE4SS/src/LuaType/LuaUObject.cpp
Creates reusable convert_lua_table_to_struct and convert_struct_to_lua_table helper functions
- Extract convert_lua_table_to_struct and convert_struct_to_lua_table from push_structproperty to helper functions
- Add special handling for arrays with unsupported inner types
- Replace inline lambdas
Tested in a couple of games. More testing requested
**Checklist**
=> refactor(lua): create struct conversion helpers from push_structproperty

UE4SS/include/ExceptionHandling.hpp, UE4SS/include/UE4SSProgram.hpp, UE4SS/src/UE4SSProgram.cpp, UE4SS/src/main_ue4ss_rewritten.cpp, assets/Changelog.md
The game thread is immediately unblocked after the scan, and then init continues asynchronously as usual.
Tested with Palworld by making sure everything inits properly, and making sure it fails correctly with an improper UE4SS_Signature file to simulate an AOB not being found.
**Checklist**
Dependent on https://github.com/Re-UE4SS/UEPseudo/pull/149
=> feat(Init): Do a single scan while blocking the game thread

UE4SS/src/LuaType/LuaUObject.cpp, assets/Changelog.md
- Implement TArray userdata handling in push_arrayproperty::lua_to_memory
- Support copying TArray userdata to function parameters
- Handle empty arrays and proper element copying with CopySingleValueToScriptVM
Enables passing TArray properties as function parameters, matching TSet functionality
Tested passing TArray properties as function parameters
Verified proper handling of empty arrays and nil values
Confirmed element copying maintains data integrity
Tested with various element types (int32, string, UObject references)
**Checklist**
=> fix(lua): add TArray userdata round-trip support

UE4SS/src/LuaType/LuaFName.cpp, assets/Changelog.md, docs/upgrade-guide.md
BREAKING CHANGE: FName string constructors now default to FNAME_Add instead of FNAME_Find.
This means constructors will create new name table entries if the name doesn't exist, rather than returning NAME_None.
- Changed default FindType parameter from FNAME_Find to FNAME_Add for all string-based constructors
- Affects FName(const CharType*), FName(StringViewType), and FName(StringViewType, uint32) constructors
- Existing code relying on FNAME_Find behavior must now explicitly pass it as a parameter
Migration: Code that expects NAME_None for non-existent names should explicitly use FNAME_Find:
Before: FName TestName(TEXT("MayNotExist"));
After:  FName TestName(TEXT("MayNotExist"), FNAME_Find); …
=> refactor(FName)!: default to FNAME_Add for string constructors

UE4SS/generated_include/MacroSetter.hpp, UE4SS/include/LuaType/LuaUDataTable.hpp, UE4SS/src/LuaType/LuaUDataTable.cpp, UE4SS/src/LuaType/LuaUObject.cpp, UE4SS/src/UE4SSProgram.cpp, assets/Changelog.md, assets/Mods/shared/Types.lua
Adds comprehensive UDataTable support to the Lua (and C++) APIs, enabling reading and manipulation of DataTable assets at runtime. This feature allows Lua mods to access row data from DataTables, iterate through rows, find specific entries, and modify DataTable contents dynamically.
Tested all operations in 4.22+ games with standard UE4SS configuration. Tested all operations in 4.21 and less games with LessEqual421 configuration
**Checklist**
ForeachRow in C++ is named without a capital E, but uses a capital E in the Lua api. This is so the C++ api continues to follow UE, while our Lua api follows our normal conventions.
=> Lua DataTable support

cppmods/KismetDebuggerMod/src/KismetDebugger.cpp
update kismetdebuggermod for imgui updates causing warnings related to using SetCursorPos without passing an imgui item afterwards
**Checklist**
=> fix: update kismetdebuggermod for imgui updates causing warnings

deps/first/Helpers/include/Helpers/String.hpp
Before this, the diagnostic was only pushed on non-Windows platforms, but it was popped on all platforms, so not only was the logic incorrect, but the push/pop was uneven which caused warnings when using Clang on Windows.
=> fix(Build): Clang is available on Windows as well, and as such, we need to push/pop diagnostics there too

assets/CustomGameConfigs/Silent Hill F/MemberVariableLayout.ini
Silent Hill F has offset member variables. Using the UE 5.4 MemberVariableLayout template as a baseline, this adds a MemberVariableLayout.ini that offsets UStruct, UClass, and UFunction by -0x10 to resolve the issue. UE4SS loads and functions as expected.
Fixes 
I created a mod that interacts with Kismet, PPVs, and various other objects/functions and verified the mod functionality. I examined several objects in memory with live view and experienced no crashes. There were no errors in the log.
=> Silent Hill F CustomGameConfig

UE4SS/include/LuaLibrary.hpp, UE4SS/src/LuaLibrary.cpp, UE4SS/src/Mod/LuaMod.cpp, UE4SS/src/Signatures.cpp, deps/first/SinglePassSigScanner/src/SinglePassSigScanner.cpp, docs/SUMMARY.md, docs/guides/fixing-compatibility-problems.md, docs/lua-api/global-functions/loadexport.md
This function takes a decorated symbol name, and returns either nil or the address of the symbol as an integer.
It's available both for UE4SS_Signatures Lua files, and also main.lua for regular mods, though I suspect it won't be particularly useful there.
You are no longer required to use the `Register` and `OnMatchFound` functions for Lua files in the `UE4SS_Signatures` directory.
Instead, you can use `LoadExport` and return its return value at file-scope.
Note that this only works if the game exports the symbol.
This is usually only the case if the game is built modularly, like Satisfactory.
Example:
```lua
-- UE4SS_Signatures/GUObjectArray.lua
return LoadExport("?GUObjectArray@@3VFUObjectArray@@A")
```
=> Adds `LoadExport` function, and the ability for UE4SS_Signatures Lua files to return the address instead of using the two global functions

UE4SS/include/SettingsManager.hpp, UE4SS/src/SettingsManager.cpp, UE4SS/src/UE4SSProgram.cpp, assets/CustomGameConfigs/Atomic Heart/UE4SS-settings.ini, assets/CustomGameConfigs/Borderlands 3/UE4SS-settings.ini, assets/CustomGameConfigs/Deadly Days Roadtrip/UE4SS-settings.ini, assets/CustomGameConfigs/Final Fantasy 7 Rebirth/UE4SS-settings.ini, assets/CustomGameConfigs/Final Fantasy 7 Remake/UE4SS-settings.ini, assets/CustomGameConfigs/Kingdom Hearts 3/UE4SS-settings.ini, assets/CustomGameConfigs/Lies of P/UE4SS-settings.ini, assets/CustomGameConfigs/Split Fiction/UE4SS-settings.ini, assets/CustomGameConfigs/Star Wars Jedi Survivor/UE4SS-settings.ini, assets/CustomGameConfigs/The Outer Worlds Spacer's Choice/UE4SS-settings.ini, assets/CustomGameConfigs/The Outer Worlds/UE4SS-settings.ini, assets/UE4SS-settings.ini
If set to `0`, the entire first phase will be skipped, restoring behavior what it was before #985
Test both values in UE4SS-settings.ini, and make sure the `Phase 1` / `Phase 2` messages in UE4SS.log appear appropriately and that no crash occurs.
=> feat: Added DoEarlyScan to UE4SS-settings.ini
