UE4SS-RE/RE-UE4SS

src/GUI/LiveView.cpp

The left offset relative to the owner of the struct.
The right offset is relative to the struct itself.

Added a recursive tree-view for StructProperty values in LiveView.

---

src/GUI/Dumpers.cpp

Mostly Bored - FStaticMaterial split into two structs for <=4.19 and >=4.20.
Tested and working on several game/UE versions.

Merge in Mostly Bored's PR #10 to allow single DLL

---

include/GUI/LiveView.hpp
src/GUI/LiveView.cpp

Gives you an overview of your view history and makes it a lot easier to navigate it.

Added a context menu to the '<<<' and '>>>' buttons.

---

include/Mod.hpp
src/Mod.cpp

See commit message for details.

Fixed crash on game close.

---

src/Mod.cpp

This commit is dependent on the commit by the same name in UEPseudo.

Fixed FFrame incompatibility in 5.1.

---

include/SDKGenerator/UEHeaderGenerator.hpp
src/SDKGenerator/UEHeaderGenerator.cpp

Keep this pull request open until it's been confirmed to work properly.

The UHT compatible generator now auto-generates 'GetTypeHash' functions.

---

CustomGameConfigs/Star Wars Jedi Fallen Order/MemberVariableLayout.ini

The 'UClass' class is customized.

Added config for Jedi Fallen Order.

---

src/SDKGenerator/UEHeaderGenerator.cpp

(#36) Fix UHT build.cs generation

---

include/GUI/LiveView.hpp
src/GUI/LiveView.cpp

Arrays in the live view can now be expanded to view each array element.

Array expansion in the live view.

---

src/SDKGenerator/Generator.cpp

In the cases where it no longer halts, it will skip whatever thing it was trying to generate.
For example, if it was trying to generate a UFunction parameter, the entire UFunction will skipped.

The CXX generator now keeps going in some circumstances instead of halting.

---

Readme.md

Also updated the build-status SVG for 2.XDev to the new action because the old one was replaced.

Added build-status for the release branch.

---

src/GUI/LiveView.cpp

This checks if an object or any of its outers is a pawn that's controlled by the player and makes the result visible in the live view GUI.

Added 'Player Controlled' to the live view tab.

---

CMakeLists.txt
include/SDKGenerator/Common.hpp
src/SDKGenerator/Common.cpp
src/SDKGenerator/UEHeaderGenerator.cpp

Remove fmt lib and uses of fmt::format in favor of std::format

Remove fmt lib

---

CMakeLists.txt
assets/Changelog.md
assets/UE4SS-settings.ini
include/GUI/LiveView.hpp
include/GUI/SearcherWidget.hpp
include/GUI/UFunctionCallerWidget.hpp
include/SettingsManager.hpp
src/GUI/LiveView.cpp
src/GUI/SearcherWidget.cpp
src/GUI/UFunctionCallerWidget.cpp
src/SettingsManager.cpp
tools/buildscripts/build.py

Adds ability to call an object's UFunctions from a window within the live view debugging GUI.

Call UFunctions from Live View GUI

---

include/Mod/LuaMod.hpp
src/Mod/LuaMod.cpp

my apologies, I'm merging these changes down from a ver with a lot more changes that aren't ready for PR and missed this line.
this does build clean locally, but I left that line staged for commit.

fix build error introduced by #144

---

include/Mod/CppMod.hpp
src/Mod/CppMod.cpp

Added functionality to allow cpp mods to include dynamic dlls to link

added AddDllDirectory and RemoveDllDirectory to CppMod

---

docs/guides/creating-a-c++-mod.md

Added a section for installing the mod

Update 'Creating a C++ Mod Guide'

---

Dependencies/Function/include/Function/Function.hpp
assets/Changelog.md
include/LuaType/LuaFText.hpp
src/LuaType/LuaFText.cpp
src/LuaType/LuaUObject.cpp
src/Mod/LuaMod.cpp
src/SDKGenerator/UEHeaderGenerator.cpp
src/Signatures.cpp

This fixes the FText implementation

FText fixes

---

assets/CustomGameConfigs/SCP 5K/Readme.md
assets/CustomGameConfigs/SCP 5K/UE4SS_Signatures/FName_Constructor.lua
assets/CustomGameConfigs/SCP 5K/UE4SS_Signatures/FName_ToString.lua

As the readme suggests, this game is in early access and updates often, so I imagine these may break at some point.
Thanks for the docs, I found them helpful.

Add SCP: 5K signatures

---

.git-blame-ignore-revs

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

Add clang format commit to .git-blame-ignore-revs

---

UE4SS/CMakeLists.txt
UE4SS/include/CrashDumper.hpp
UE4SS/include/SettingsManager.hpp
UE4SS/include/UE4SSProgram.hpp
UE4SS/src/CrashDumper.cpp
UE4SS/src/SettingsManager.cpp
UE4SS/src/UE4SSProgram.cpp
assets/UE4SS-settings.ini

This crash handler allows for crashdump generation.

added crash handler

---

CMakeLists.txt
UE4SS/CMakeLists.txt
deps/third/CMakeLists.txt
deps/third/PolyHook_2_0/CMakeLists.txt
deps/third/imgui/CMakeLists.txt
deps/third/raw_pdb/CMakeLists.txt
deps/third/zydis/CMakeLists.txt

CMake refactors for third-party deps / Add glaze json library

---

assets/Mods/BPML_GenericFunctions/Scripts/main.lua

It wasn't returning the constructed object properly.

Fixed 'ConstructPersistentObject' in BPML_GenericFunctions

---

UE4SS/proxy_generator/proxy/CMakeLists.txt

Per #262, this improves compatibility across different games.

Change default proxy dll to dwmapi.dll

---

UE4SS/src/LuaType/LuaUEnum.cpp
assets/Mods/shared/Types.lua
docs/lua-api/classes/uenum.md

Added LUA bindings for the following UEnum funcitons:
- GetEnumNameByIndex
- InsertIntoNames
- EditNameAt
- EditValueAt
- RemoveFromNamesAt
DRAFT: Implementations are still POC. There's also likely more documentation that could be added, alongside actual LUA helpers.

feat: Added LUA bindings for enum mutation functions

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Please include a summary of the change and which issue is fixed. Include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so reviewers can reproduce. Please also list any relevant details for your test configuration.
**Checklist**
Add any other context about the pull request here.

PR template

---

.github/ISSUE_TEMPLATE/bug_report.md

See e4daafd2a0fd4663609a1a32a1a84715fc686852
Please describe the tests that you ran to verify your changes. Provide instructions so reviewers can reproduce. Please also list any relevant details for your test configuration.
**Checklist**
Note that I did not update the changelog because I don't consider this type of change to be something that needs to be logged for the public, and for internal use there's the commit history.

Added .dmp file alongside log file to the bug report template

---

assets/Changelog.md
assets/UE4SS-settings.ini

See commit message
Please describe the tests that you ran to verify your changes. Provide instructions so reviewers can reproduce. Please also list any relevant details for your test configuration.
**Checklist**
Add any other context about the pull request here.

Added 'HookLoadMap' to UE4SS-settings.ini

---

deps/first/Function/include/Function/Function.hpp

Fixes compilation error for external projects using the Function.hpp header
**Checklist**

Fix compilation error for Function.hpp

---

assets/Changelog.md
assets/Mods/BPModLoaderMod/Scripts/main.lua

Fixes loading on slow dedicated servers where UE4SS initializes too
late.
Please describe the tests that you ran to verify your changes. Provide instructions so reviewers can reproduce. Please also list any relevant details for your test configuration.
**Checklist**

fix(BPModLoader): Loading on slow dedicated servers

---

.github/pull_request_template.md
assets/Changelog.md
docs/feature-overview/live-view.md

Proper live view docs, slight change to pr template, fixed the formatting for 3.1.0 changelog to be inline with the previously defined format from 3.0.1.
Please review the live view docs and check for errors or suggest changes.

Bits n bobs I've been meaning to do for a while

---

README.md
tools/xmakescripts/build_configs.lua

Fixes #462 
Bug fix (non-breaking change which fixes an issue)
Tested with `xmake` from cmd and tested with VS2022 generated project.

Add optimization and symbols for xmake build

---

docs/SUMMARY.md
docs/cpp-api.md
docs/cpp-api/cpp-examples.md
docs/guides/creating-a-c++-mod.md
docs/guides/installing-a-c++-mod.md
docs/lua-api.md

- added clarification to c++ mod dcos
- removed page entries (but not deleted actual pages) for experimental and universal ue mods because they are both empty and that likely won't change for the foreseeable future
**Checklist**

Minor docs changes

---

UE4SS/include/LuaCustomMemberFunctions.hpp
UE4SS/include/LuaType/LuaTArray.hpp
UE4SS/src/LuaType/LuaUObject.cpp
UE4SS/src/SDKGenerator/UEHeaderGenerator.cpp

Moves certain UEPseudo files to be in proper locations to simplify later PRs
Will require changes to includes if mods happened to use these files.
Builds; no changes to functionality
**Checklist**

Updates for UEPseudo file moves; update UE submodule

---

UE4SS/include/LuaType/LuaUObject.hpp
UE4SS/src/CrashDumper.cpp
UE4SS/src/GUI/BPMods.cpp
UE4SS/src/GUI/Dumpers.cpp
UE4SS/src/GUI/LiveView.cpp
UE4SS/src/GUI/UFunctionCallerWidget.cpp
UE4SS/src/LuaLibrary.cpp
UE4SS/src/LuaType/LuaTArray.cpp
UE4SS/src/LuaType/LuaUObject.cpp
UE4SS/src/LuaType/LuaUScriptStruct.cpp
UE4SS/src/Mod/CppUserModBase.cpp
UE4SS/src/Mod/LuaMod.cpp
UE4SS/src/ObjectDumper/ObjectToString.cpp
UE4SS/src/SDKGenerator/Common.cpp
UE4SS/src/SDKGenerator/Generator.cpp
UE4SS/src/SDKGenerator/UEHeaderGenerator.cpp
UE4SS/src/UE4SSProgram.cpp
UE4SS/xmake.lua
deps/first/DynamicOutput/include/DynamicOutput/Output.hpp
deps/first/DynamicOutput/src/OutputDevice.cpp
deps/first/File/src/FileType/WinFile.cpp
deps/first/File/xmake.lua
deps/first/IniParser/src/JSON.cpp
deps/first/IniParser/src/TokenParser.cpp
deps/first/LuaMadeSimple/include/LuaMadeSimple/LuaMadeSimple.hpp
deps/first/LuaMadeSimple/src/LuaMadeSimple.cpp
deps/first/LuaMadeSimple/xmake.lua
deps/first/SinglePassSigScanner/src/SinglePassSigScanner.cpp
deps/first/SinglePassSigScanner/xmake.lua

Ironically I was the one that removed it a year or two ago.

Adds back fmt lib for better handling of types when formatting

---

assets/Changelog.md
deps/first/patternsleuth_bind/Cargo.toml
deps/first/xmake.lua

Fixes several issues with resolving
**Checklist**

Update Pattern Sleuth

---

assets/Mods/shared/Types.lua

Nothing special, just added Lua Annotations for FName, FText and TArray functions

feat(Types.lua): Add type descriptions for FName, FText and TArray functions

---

assets/Changelog.md
deps/first/Input/include/Input/KeyDef.hpp

Fixed Key::NUM_ZERO being mapped incorrectly to NUM_NINE

---

assets/Mods/BPML_GenericFunctions/Scripts/main.lua
assets/Mods/BPModLoaderMod/Scripts/main.lua
assets/Mods/CheatManagerEnablerMod/Scripts/main.lua
assets/Mods/ConsoleCommandsMod/Scripts/main.lua
assets/Mods/LineTraceMod/Scripts/main.lua
assets/Mods/SplitScreenMod/Scripts/main.lua

Add `[ModName] ` to the log messages of all built-in mods that have log messages, so it is 100% clear which mod does each error message come from. Also added a few missing line endings to log messages here and there.
- [Y] Other... Please describe: minor refactoring
I enabled all built-in mods and ran them.
**Checklist**
- [Y] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries.

chore: include mod names in logs of built-in Lua mods

---

UE4SS/src/Signatures.cpp
UE4SS/src/UE4SSProgram.cpp
assets/Changelog.md
deps/first/patternsleuth_bind/src/lib.rs
docs/guides/fixing-compatibility-problems.md

Add ability to signify a scan result is optional in patternsleuth_bind
Make FText(FString&&) scan optional
Update Patternsleuth
Add optional scans for GUObjectHashTables::Get(), GNatives, ConsoleManager::Singleton
Update UE Submodule for new scans
Add Lua override scripts for new scans; add warning if GNatives is not found
Tested on several games
**Checklist**

Add ability to signify a scan result is optional in patternsleuth_bind; add optional scans

---

README.md

This was done to be consistent with the terminology in the full installation guide.

Changed 'Gameroot' to 'game directory' in basic installation section of readme

---

UE4SS/include/UE4SSProgram.hpp
UE4SS/src/Mod/CppUserModBase.cpp
UE4SS/src/Mod/LuaMod.cpp
UE4SS/src/UE4SSProgram.cpp
deps/first/Input/include/Input/Handler.hpp
deps/first/Input/include/Input/KeyDef.hpp
deps/first/Input/xmake.lua

Internal PR, see commits.
Don't merge, I will do it.

Inputsource ifdef2

---

docs/SUMMARY.md
docs/guides/accessing-ue-properties-c++.md

This PR adds a simple guide for reading and writing UE properties.
It's mostly just code examples.

Added guide for accessing C++ properties to docs

---

UE4SS/src/GUI/LiveView.cpp
assets/Changelog.md

This PR fixes a crash in the Live View tab.
**Checklist**
Do not merge until #768 and #769 has been merged, or if they don't get merged, rebase onto main or cherry-pick this commit.

Fixed use of invalid iterator in Live View

---

UE4SS/src/LuaType/LuaUObject.cpp
assets/Changelog.md

Fixes #774
See the code example in #774
**Checklist**

Fixed Lua table-in-table processing

---

UE4SS/src/Mod/LuaMod.cpp
assets/Changelog.md
docs/lua-api/global-functions/registerhook.md

Fixes #799 
See #799 for test, and the comment below for the results, but tldr, it was a success.
**Checklist**

fix(Lua): Script hooks corrupts original function return value

---

UE4SS/src/Mod/LuaMod.cpp
assets/Changelog.md

fix(Lua): Locking when registering and unregistering custom events

---

.github/workflows/experimental.yml
.github/workflows/release.yml

fix(CI): Lock MSVC to 19.42

---

assets/Changelog.md
tools/buildscripts/release.py

- LineTraceMod, ActorDumperMod & jsbLuaProfilerMod are removed from Mods/ and their entries removed from mods.txt/.json
- Mods/shared/jsbProfiler is removed
- README.md & Changelog.md are removed from non-dev release
- Added LICENCE file to both release types
Ran release script locally and checked contents of release zips.
**Checklist**

Change which files are included in the non-dev release

---

UE4SS/src/Mod/LuaMod.cpp
assets/Changelog.md
docs/upgrade-guide.md

Allows use of the template as intended
Updated source to use new form.
**Checklist**

Convert simple TObjectPtr impl to proper smart pointer

---

UE4SS/include/SettingsManager.hpp
UE4SS/src/GUI/LiveView.cpp
UE4SS/src/SettingsManager.cpp
assets/Changelog.md
assets/CustomGameConfigs/Final Fantasy 7 Rebirth/UE4SS-settings.ini
assets/CustomGameConfigs/Final Fantasy 7 Remake/UE4SS-settings.ini
assets/CustomGameConfigs/Lies of P/UE4SS-settings.ini
assets/CustomGameConfigs/Split Fiction/UE4SS-settings.ini
assets/UE4SS-settings.ini
tools/buildscripts/release.py

This feature is no longer tied to an option in UE4SS-settings.ini.
**Checklist**

chore: Promote GUIUFunctionCaller out of the experimental feature-set

---

UE4SS/src/LuaType/LuaUObject.cpp
UE4SS/src/ObjectDumper/ObjectToString.cpp
UE4SS/src/SDKGenerator/Common.cpp
UE4SS/src/SDKGenerator/Generator.cpp
UE4SS/src/SDKGenerator/UEHeaderGenerator.cpp
assets/Default_UVTD_Configs/Config/object_items.json
assets/Default_UVTD_Configs/Config/types_not_to_dump.json
assets/Default_UVTD_Configs/Config/virtual_generator_includes.json
docs/upgrade-guide.md

Updates to source for TObjectPtr api changes and to start move to safer pointer use. Requires merge of https://github.com/Re-UE4SS/UEPseudo/pull/126.
Compiles and runs as expected.
**Checklist**

Updates to source for TObjectPtr api changes and to start move to safer pointer use

---

UE4SS/src/GUI/ImGuiUtility.cpp
UE4SS/xmake.lua
assets/Changelog.md
deps/first/Constructs/include/Constructs/Generator.hpp
deps/first/LuaMadeSimple/include/LuaMadeSimple/LuaObject.hpp
deps/third-repo/packages/i/imguitextedit/xmake.lua
deps/third-repo/packages/z/zycore/xmake.lua
deps/third-repo/packages/z/zydis/xmake.lua
deps/xmake.lua

Minor syntax/code fixes to allow compilation with Clang.

Clang fixes

---

UE4SS/include/LuaType/LuaUObject.hpp
UE4SS/src/LuaType/LuaUObject.cpp

Somehow this was missed a while back.

fix(Lya): Added missing 'Set' function to Local/RemoteUnrealParam

---

UE4SS/src/CrashDumper.cpp
UE4SS/src/UE4SSProgram.cpp
deps/first/DynamicOutput/src/OutputDevice.cpp

Wine hasn't implemented a few chrono functions, including `__std_tzdb_get_time_zones` which is required for `std::chrono::current_zone()`.
This PR reverts to using UTC if wine is detected.

fix: chrono::current_zone unimplemented in wine causing a crash when using wine

---

UE4SS/src/GUI/GUI.cpp
UE4SS/src/GUI/LiveView.cpp
UE4SS/xmake.lua
assets/Changelog.md
deps/first/DynamicOutput/include/DynamicOutput/Output.hpp
deps/third-repo/packages/f/fmt/xmake.lua
deps/third-repo/packages/i/imguitextedit/xmake.lua
deps/third-repo/packages/p/polyhook_2/xmake.lua
deps/third-repo/packages/z/zydis/xmake.lua
deps/xmake.lua
tools/xmakescripts/rules/build_rules.lua

Updates ImGui from v1.91.9b to 1.92.1 and updates fmt library to 11.2.0, as well as updates API calls for compatibility. This change is necessary to maintain compatibility with the latest versions of these dependencies and to support Clang compilation.
Compiles and runs.
**Checklist**

Xmakeupdates

---

UE4SS/src/UE4SSProgram.cpp
assets/UE4SS-settings.ini
tools/buildscripts/release.py

Fixes us not properly reading the first line in mods.txt due to UTF8 BOM signature. Fixes our release script adding such signature.
**Checklist**

Skipbom fixbom

---

deps/first/SinglePassSigScanner/src/SinglePassSigScanner.cpp

fix(scanner): updates the lua scanner to only scan readable memory
